version: '3'

services:
  db:
    image: 'mariadb:latest'
    container_name: scala-api-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: scala_api
      MYSQL_USER: haroldport
      MYSQL_PASSWORD: har0ld
    ports:
      - ${SCALA_API_DB_PORT}:3306

  broker:
    image: 'rabbitmq:3.7.8-management'
    container_name: scala-api-broker
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: haroldport
      RABBITMQ_DEFAULT_PASS: har0ld
    ports:
      - ${SCALA_API_BROKER_PORT}:5672
      - ${SCALA_API_BROKER_ADMIN_PORT}:15672
